# RTL8821CE / rtw88_8821ce stability: disable deep power-save + PCIe ASPM + MSI
# Refs:
#   https://bbs.archlinux.org/viewtopic.php?id=273440
#   https://bbs.archlinux.org/viewtopic.php?id=293187
options rtw88_core disable_lps_deep=y
options rtw88_pci disable_msi=y disable_aspm=y
