windowrule = suppress_event maximize, match:class .*

windowrule = float on, match:class ^(pavucontrol|nm-connection-editor|blueman-manager)$
windowrule = center on, match:class ^(pavucontrol|nm-connection-editor|blueman-manager)$
windowrule = size 900 620, match:class ^(pavucontrol|nm-connection-editor|blueman-manager)$

windowrule = workspace 2, match:class ^(firefox)$
windowrule = workspace 3, match:class ^(Code|code-oss)$
