windowrule = suppress_event maximize, match:class .*
windowrule = center on, match:float true

workspace = 1, persistent:true, defaultName:web
workspace = 2, persistent:true, defaultName:code
workspace = 3, persistent:true, defaultName:chat
workspace = 4, persistent:true, defaultName:shell
workspace = 5, persistent:true, defaultName:media
workspace = 6, persistent:true, defaultName:files
workspace = 7, persistent:true, defaultName:docs
workspace = 8, persistent:true, defaultName:tools
workspace = 9, persistent:true, defaultName:misc
workspace = 10, persistent:true, defaultName:extra

windowrule = float on, match:class ^(org\.pulseaudio\.pavucontrol|nm-connection-editor|blueman-manager|AmneziaVPN)$
windowrule = center on, match:class ^(org\.pulseaudio\.pavucontrol|nm-connection-editor|blueman-manager|AmneziaVPN)$
windowrule = size 900 620, match:class ^(org\.pulseaudio\.pavucontrol|nm-connection-editor|blueman-manager)$

windowrule = workspace 1, match:class ^(firefox|Firefox|Brave-browser|brave-browser|Chromium|chromium|Google-chrome|google-chrome)$
windowrule = workspace 2, match:class ^(Code|code|code-oss|VSCodium|codium)$
windowrule = workspace 3, match:class ^(discord|vesktop|TelegramDesktop|org\.telegram\.desktop)$
windowrule = workspace 5, match:class ^(Spotify|spotify)$
windowrule = workspace 6, match:class ^(nemo)$
